name: zxplore_app
description: A Cross Platform Mobile app for Account Creation By Zenith Staff

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.3+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  intl: ^0.15.8
  image_picker: ^0.6.0+3
  sqflite: ^1.1.7+1
  path_provider: ^1.1.0
  http: ^0.12.0+2
  encrypt: ^3.0.0
  shared_preferences: ^0.5.2
  flutter_secure_storage: ^3.2.1+1
  crypto: ^2.0.6
  dio: ^2.1.7
  flushbar: ^1.5.0
  meta: ^1.1.6
  equatable: ^0.5.0
  catcher: ^0.2.3

dev_dependencies:

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/zenithLogo.svg
    - assets/accountType.json
    - assets/images/logo.png
    - assets/images/zenithheader.jpg
    - assets/images/view_offline.png
    - assets/images/accept_signature.png
    - assets/images/create_account.png
    - assets/server_certificate.crt
